[guard]
header = [
    "0x71", "0x11", "0x34", "0x78",
    "0x7e", "0x6f", "0x04", "0x6a",
    "0xdf", "0x08", "0x46", "0x1c",
]
key = [
    "0xcf", "0x9a", "0x37", "0xeb",
    "0x15", "0x3c", "0x03", "0x9b",
    "0xee", "0x59", "0x2f", "0xf0",
    "0xc0", "0xdd", "0xc5", "0xa2",
]
